name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    name: Run CI
    env:
      # Setting GOTOOLCHAIN to local tells go
      # to to use the bundled Go version rather
      # than fetching the toolchain according to
      # toolchain directive found in go.mod.
      # See: https://brandur.org/fragments/go-version-matrix
      GOTOOLCHAIN: local
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        go:
          - '1.22'
          - '1.23'

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v4

    - name: Cache the build cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-${{ matrix.go }}-go-ci-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.go }}-go-ci-

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -shuffle=on -v ./...

  lint:
    name: Run linter
    env:
      # Setting GOTOOLCHAIN to local tells go
      # to to use the bundled Go version rather
      # than fetching the toolchain according to
      # toolchain directive found in go.mod.
      # See: https://brandur.org/fragments/go-version-matrix
      GOTOOLCHAIN: local
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        go:
          - '1.22'
          - '1.23'

    steps:

    - name: Check out source code
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.60
